// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bajyxxovdprptqajfqty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhanl4eG92ZHBycHRxYWpmcXR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5OTA0NzksImV4cCI6MjA2MzU2NjQ3OX0.GbVwbhN0pv5BZD6UxHfz5SklTTDJjXp8g8DygFrqAxs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);